version: '3'

services:
  minio:
    image: minio/minio:latest
    command: server /export
    environment:
    - MINIO_ACCESS_KEY=access_key
    - MINIO_SECRET_KEY=secret_key
    ports:
    - "9009:9000"
    volumes:
    - ./minio/data/export:/export
    - ./minio/data/.minio:/root/.minio
    networks:
    - db

networks:
  db: